### ISSUE TITLE
Error in endpoint connection using token from tastytrade

### ISSUE THREAD

**Issue by 48574A** [dxFeed/dxfeed-graal-cxx-api#57]
I'm a tastytrade user using their sandbox environment. They've provided me a "dxlink-url": "`wss://tasty-demo-ws.dxfeed.com/delayed`" and a token. The URL and token work well in https://demo.dxfeed.com/dxlink-ws/debug/. 

I try to use `dxfcpp::DXEndpoint` for WebSocket connection to stream the feed. Here's the code snippet I use: 
```
std::shared_ptr<dxfcpp::DXEndpoint> endpoint;
endpoint = dxfcpp::DXEndpoint::create()->connect(address);
// address: "dxlink:wss://tasty-demo-ws.dxfeed.com/delayed[login=dxlink:<my_token>]"
```

But it gives error: 
```
Java exception of type 'com.devexperts.qd.qtp.AddressSyntaxException' was thrown. Port number format error in "wss://tasty-demo-ws.dxfeed.com/delayed"
```

How can I correctly use the tastytrade URL and token to establish a WebSocket connection?

**Comment by AnatolyKalin** [comment]
Hi, @48574A 

To work with dxLink, please set these properties.
They are important and enable this feature and the required schema.

```cpp
    // Enable experimental feature.
    System::setProperty("dxfeed.experimental.dxlink.enable", "true");
    // Set scheme for dxLink.
    System::setProperty("scheme", "ext:opt:sysprops,resource:dxlink.xml");
```

See: https://github.com/dxFeed/dxfeed-graal-cxx-api?tab=readme-ov-file#how-to-connect-to-dxlink

**Comment by 48574A** [comment]
Thanks @AnatolyKalin! 
The WebSocket connection is working well now.
